"""Export utilities to generate Ollama Modelfile and InferOps runtime manifests."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import yaml

from quantforge.formats.gguf_reader import GGUFReader

# Standard architecture-to-template heuristics when tokenizer.chat_template is omitted
DEFAULT_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "llama": {
        "template": '{{ if .System }}<|start_header_id|>system<|end_header_id|>\n\n{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>\n\n{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>\n\n{{ .Response }}<|eot_id|>',
        "stops": ["<|eot_id|>", "<|start_header_id|>", "<|end_header_id|>"],
    },
    "mistral": {
        "template": "[INST] {{ if .System }}{{ .System }}\n\n{{ end }}{{ .Prompt }} [/INST] {{ .Response }}",
        "stops": ["</s>", "[INST]"],
    },
    "qwen2": {
        "template": "{{ if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}{{ if .Prompt }}<|im_start|>user\n{{ .Prompt }}<|im_end|>\n{{ end }}<|im_start|>assistant\n{{ .Response }}<|im_end|>",
        "stops": ["<|im_end|>", "<|im_start|>"],
    },
    "gemma": {
        "template": "<start_of_turn>user\n{{ if .System }}{{ .System }}\n\n{{ end }}{{ .Prompt }}<end_of_turn>\n<start_of_turn>model\n{{ .Response }}<end_of_turn>",
        "stops": ["<end_of_turn>"],
    },
    "phi3": {
        "template": "{{ if .System }}<|system|>\n{{ .System }}<|end|>\n{{ end }}{{ if .Prompt }}<|user|>\n{{ .Prompt }}<|end|>\n{{ end }}<|assistant|>\n{{ .Response }}<|end|>",
        "stops": ["<|end|>", "<|user|>"],
    },
    "chatml": {
        "template": "{{ if .System }}<|im_start|>system\n{{ .System }}<|im_end|>\n{{ end }}{{ if .Prompt }}<|im_start|>user\n{{ .Prompt }}<|im_end|>\n{{ end }}<|im_start|>assistant\n{{ .Response }}<|im_end|>",
        "stops": ["<|im_end|>", "<|im_start|>"],
    },
}


@dataclass
class ExportPackage:
    """Artifact containing Ollama Modelfile text and InferOps configuration."""

    model_name: str
    gguf_path: str
    modelfile_content: str
    inferops_yaml_content: str
    inferops_json_content: str
    context_length: int
    architecture: str


class ModelExporter:
    """Generates production-grade Ollama Modelfiles and InferOps deployment manifests."""

    def __init__(self, gguf_path: Union[str, Path]):
        self.gguf_path = Path(gguf_path).resolve()
        if not self.gguf_path.is_file():
            raise FileNotFoundError(f"GGUF model file not found: {self.gguf_path}")

        reader = GGUFReader(self.gguf_path)
        self.info = reader.read_model_info(load_tensors=False)
        self.arch = (self.info.architecture or "llama").lower()
        self.context_length = self.info.context_length or 4096
        self.model_name = self.gguf_path.stem

    def generate_modelfile(
        self,
        temperature: float = 0.7,
        top_p: float = 0.9,
        system_prompt: Optional[str] = None,
        custom_template: Optional[str] = None,
    ) -> str:
        """Constructs an Ollama Modelfile text with correct stops, parameters, and template."""
        lines = [
            f"# Generated by QuantForge for {self.model_name}",
            f'FROM "{self.gguf_path.as_posix()}"',
            f"PARAMETER num_ctx {self.context_length}",
            f"PARAMETER temperature {temperature}",
            f"PARAMETER top_p {top_p}",
        ]

        # Stop tokens & template
        template_info = DEFAULT_TEMPLATES.get(self.arch, DEFAULT_TEMPLATES["llama"])
        chat_template = custom_template or self.info.metadata.get("tokenizer.chat_template") or template_info["template"]
        stops: List[str] = template_info.get("stops", [])

        for stop in stops:
            lines.append(f'PARAMETER stop "{stop}"')

        if system_prompt:
            lines.append(f'SYSTEM """{system_prompt}"""')

        lines.append(f'TEMPLATE """{chat_template}"""')
        return "\n".join(lines) + "\n"

    def generate_inferops_config(
        self,
        gpu_layers: int = -1,
        threads: Optional[int] = None,
        port: int = 8080,
    ) -> Dict[str, Any]:
        """Produces a structured InferOps service specification."""
        return {
            "version": "1.0",
            "service": {
                "name": self.model_name,
                "engine": "llama.cpp",
                "model_path": str(self.gguf_path),
                "quant_type": self.info.dominant_quant or "UNKNOWN",
                "architecture": self.arch,
                "server": {
                    "host": "0.0.0.0",
                    "port": port,
                },
                "parameters": {
                    "context_size": self.context_length,
                    "gpu_layers": gpu_layers,
                    "threads": threads if threads is not None else 8,
                    "batch_size": 512,
                    "temperature": 0.7,
                    "top_p": 0.9,
                },
            },
        }

    def export(
        self,
        output_dir: Optional[Union[str, Path]] = None,
        system_prompt: Optional[str] = None,
    ) -> ExportPackage:
        """Exports both Modelfile and inferops.yaml, writing to disk if output_dir is given."""
        modelfile = self.generate_modelfile(system_prompt=system_prompt)
        inferops_dict = self.generate_inferops_config()
        inferops_yaml = yaml.dump(inferops_dict, default_flow_style=False, sort_keys=False)
        inferops_json = json.dumps(inferops_dict, indent=2)

        if output_dir:
            out = Path(output_dir)
            out.mkdir(parents=True, exist_ok=True)

            modelfile_path = out / "Modelfile"
            modelfile_path.write_text(modelfile, encoding="utf-8")

            yaml_path = out / "inferops.yaml"
            yaml_path.write_text(inferops_yaml, encoding="utf-8")

        return ExportPackage(
            model_name=self.model_name,
            gguf_path=str(self.gguf_path),
            modelfile_content=modelfile,
            inferops_yaml_content=inferops_yaml,
            inferops_json_content=inferops_json,
            context_length=self.context_length,
            architecture=self.arch,
        )
